import postImg from "../assets/images/postImg.png";
import userDp from "../assets/images/userDp.png";
export const users = [
  {
    id: 1,
    avatar: userDp,
    name: "Guy Hawkins",
    date: "2/11/12",
  },
  {
    id: 2,
    avatar: userDp,
    name: "Devon Lane",
    date: "9/23/16",
  },
  {
    id: 3,
    avatar: userDp,
    name: "Dianne Russell",
    date: "3/4/16",
  },
  {
    id: 4,
    avatar: userDp,
    name: "Marvin McKinney",
    date: "10/6/13",
  },
  {
    id: 5,
    avatar: userDp,
    name: "Jane Cooper",
    date: "5/30/14",
  },
];

export const posts = [
  {
    id: 1,
    name: "Ben Davis",
    date: "28/07/1997",
    time: "2 hours",
    postText:
      "I’m so grateful to see another birthday today, I’m also grateful to everyone for joining me to celebrate today. I really hope next year is going to be an even better celebration. Happy Birthday to me!!😊",
    images: [postImg, postImg, postImg, postImg],
    numOfComments: 26,
    userDp: userDp,
    comments: [
      {
        id: 10,
        name: "Johnson David",
        post: "Happy Birthday to you!!🎊 🎉",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [
          {
            id: 101,
            name: "You",
            time: "2021-11-11T12:36:16.592Z",
            avatar: userDp,
            post: "Thanks so much!!",
          },
        ],
      },
      {
        id: 20,
        name: "David Johnson",
        post: "Happy Birthday. Wishing you many more years ahead",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
      {
        id: 30,
        name: "Ben Peter",
        post: "Happy Birthday. Wishing you many more years ahead",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
      {
        id: 40,
        name: "Paul Jeffery",
        post: "Happy Birthday to you!!🎊 🎉",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
    ],
  },
  {
    id: 2,
    name: "Ben Davis",
    date: "28/07/1997",
    time: "2 hours",
    postText:
      "I’m so grateful to see another birthday today, I’m also grateful to everyone for joining me to celebrate today. I really hope next year is going to be an even better celebration. Happy Birthday to me!!😊",
    images: [postImg, postImg, postImg, postImg],
    numOfComments: 26,
    userDp: userDp,
    comments: [
      {
        id: 10,
        name: "Johnson David",
        post: "Happy Birthday to you!!🎊 🎉",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [
          {
            id: 101,
            name: "You",
            time: "2021-11-11T12:36:16.592Z",
            avatar: userDp,
            post: "Thanks so much!!",
          },
        ],
      },
      {
        id: 20,
        name: "David Johnson",
        post: "Happy Birthday. Wishing you many more years ahead",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
      {
        id: 30,
        name: "Ben Peter",
        post: "Happy Birthday. Wishing you many more years ahead",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
      {
        id: 40,
        name: "Paul Jeffery",
        post: "Happy Birthday to you!!🎊 🎉",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
    ],
  },
  {
    id: 3,
    name: "Ben Davis",
    date: "28/07/1997",
    time: "2 hours",
    postText:
      "I’m so grateful to see another birthday today, I’m also grateful to everyone for joining me to celebrate today. I really hope next year is going to be an even better celebration. Happy Birthday to me!!😊",
    images: [postImg, postImg, postImg, postImg],
    numOfComments: 26,
    userDp: userDp,
    comments: [
      {
        id: 10,
        name: "Johnson David",
        post: "Happy Birthday to you!!🎊 🎉",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [
          {
            id: 101,
            name: "You",
            time: "2021-11-11T12:36:16.592Z",
            avatar: userDp,
            post: "Thanks so much!!",
          },
        ],
      },
      {
        id: 20,
        name: "David Johnson",
        post: "Happy Birthday. Wishing you many more years ahead",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
      {
        id: 40,
        name: "Paul Jeffery",
        post: "Happy Birthday to you!!🎊 🎉",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
      {
        id: 30,
        name: "Ben Peter",
        post: "Happy Birthday. Wishing you many more years ahead",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
    ],
  },
  {
    id: 4,
    name: "Ben Davis",
    date: "28/07/1997",
    time: "2 hours",
    postText:
      "I’m so grateful to see another birthday today, I’m also grateful to everyone for joining me to celebrate today. I really hope next year is going to be an even better celebration. Happy Birthday to me!!😊",
    images: [postImg, postImg, postImg, postImg],
    numOfComments: 26,
    userDp: userDp,
    comments: [
      {
        id: 20,
        name: "David Johnson",
        post: "Happy Birthday. Wishing you many more years ahead",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
      {
        id: 10,
        name: "Johnson David 1",
        post: "Happy Birthday to you!!🎊 🎉",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [
          {
            id: 101,
            name: "You",
            time: "2021-11-11T12:36:16.592Z",
            avatar: userDp,
            post: "Thanks so much!!",
          },
        ],
      },
      {
        id: 30,
        name: "Ben Peter",
        post: "Happy Birthday. Wishing you many more years ahead",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
      {
        id: 40,
        name: "Paul Jeffery",
        post: "Happy Birthday to you!!🎊 🎉",
        time: "2021-11-11T12:36:16.592Z",
        avatar: userDp,
        childComments: [],
      },
    ],
  },
];
